services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: dev
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 3333:8080
